import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter} from 'next/router'
export default function Home() {
  const router = useRouter()
const handleclick=()=> {
  console.log('place Your Order')
  router.push('/product')
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog_Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
<span></span>
<Link  href='/blog'>
<a>Blog</a>
</Link>
<Link  href= '/product'>
<a>Product</a>
</Link>
<button onClick={handleclick}>Place Order</button>
      </header>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Next.js! Home</a>
        </h1>
 
        <div className={styles.grid}>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <span> </span>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >

          Powered by{' '}
          Nauman khan{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
