import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter} from 'next/router'
export default function Home() {
  const router = useRouter()
const handleclick=()=> {
  console.log('place Your Order')
  router.push('/product')
}

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog_Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <nav className="bg-white shadow" role="navigation">
  <div className="container mx-auto p-3 flex flex-wrap items-center md:flex-no-wrap">
    <div className="mr-4 md:mr-8">
      <a href="#" rel="home">
        <svg className="w-10 h-10 text-purple-600" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg">
          <title>TailwindCSS</title>
          <path fill="currentColor" d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"></path>
        </svg>
      </a>
    </div>
    <div className="ml-auto md:hidden">
      <button className="flex items-center px-3 py-2 border rounded" type="button">
        <svg className="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
        </svg>
      </button>
    </div>
    <div className="w-full md:w-auto md:flex-grow md:flex md:items-center">
      <ul className="flex flex-col mt-4 -mx-4 pt-4 border-t md:flex-row md:items-center md:mx-0 md:ml-auto md:mt-0 md:pt-0 md:border-0">
      <li>
        <Link  href='/'>
         <a className="block px-4 py-1 md:p-2 lg:px-4 text-purple-600 ">Home</a>
         </Link>    
        </li>
        <li>
        <Link  href='/product'>
         <a className="block px-4 py-1 md:p-2 lg:px-4">Products</a>
         </Link>
        </li>
        <li>
        <Link  href='/blog'>
         <a className="block px-4 py-1 md:p-2 lg:px-4">Blogs</a>
         </Link>
        </li>
        <li>
        <Link href='#'>
          <a className="block px-4 py-1 md:p-2 lg:px-4" >Help</a>
          </Link>
        </li>
        <li>
          <Link  href='/product'>
          <a className="block px-4 py-1 md:p-2 lg:px-4 text-purple-600" >Place Order</a>
          </Link>
        </li>

        <li>
          {/* // <a className="block px-4 py-1 md:p-2 lg:px-4">Sign Up</a> */}
           <button className="py-2 px-4 text-white rounded-lg bg-yellow-200 shadow-lg block md:inline-block">Sign Up</button>
        </li>
      </ul>
    </div>
  </div>
</nav>    
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Next.js! Home</a>
        </h1>
 
        <div className={styles.grid}>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <span> </span>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >

          Powered by{' '}
          Nauman khan{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
